//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 13/11/2020 17:10:38
namespace RapidAPI.Models
{
        /// <summary>
        /// There are no comments for ProjectSingle in the schema.
        /// </summary>
    public partial class ProjectSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Project>
    {
        /// <summary>
        /// Initialize a new ProjectSingle object.
        /// </summary>
        public ProjectSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ProjectSingle object.
        /// </summary>
        public ProjectSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ProjectSingle object.
        /// </summary>
        public ProjectSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Project> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Deployments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::RapidAPI.Models.Deployment> Deployments
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Deployments == null))
                {
                    this._Deployments = Context.CreateQuery<global::RapidAPI.Models.Deployment>(GetPath("Deployments"));
                }
                return this._Deployments;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::RapidAPI.Models.Deployment> _Deployments;
    }
        /// <summary>
        /// There are no comments for Project in the schema.
        /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    public partial class Project : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new Project object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static Project CreateProject(int ID)
        {
            Project project = new Project();
            project.Id = ID;
            return project;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property AppId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string AppId
        {
            get
            {
                return this._AppId;
            }
            set
            {
                this.OnAppIdChanging(value);
                this._AppId = value;
                this.OnAppIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _AppId;
        partial void OnAppIdChanging(string value);
        partial void OnAppIdChanged();
        /// <summary>
        /// There are no comments for Property AppUrl in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string AppUrl
        {
            get
            {
                return this._AppUrl;
            }
            set
            {
                this.OnAppUrlChanging(value);
                this._AppUrl = value;
                this.OnAppUrlChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _AppUrl;
        partial void OnAppUrlChanging(string value);
        partial void OnAppUrlChanged();
        /// <summary>
        /// There are no comments for Property ContainerUrl in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string ContainerUrl
        {
            get
            {
                return this._ContainerUrl;
            }
            set
            {
                this.OnContainerUrlChanging(value);
                this._ContainerUrl = value;
                this.OnContainerUrlChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ContainerUrl;
        partial void OnContainerUrlChanging(string value);
        partial void OnContainerUrlChanged();
        /// <summary>
        /// There are no comments for Property AppServicePlanId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string AppServicePlanId
        {
            get
            {
                return this._AppServicePlanId;
            }
            set
            {
                this.OnAppServicePlanIdChanging(value);
                this._AppServicePlanId = value;
                this.OnAppServicePlanIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _AppServicePlanId;
        partial void OnAppServicePlanIdChanging(string value);
        partial void OnAppServicePlanIdChanged();
        /// <summary>
        /// There are no comments for Property SqlServerId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string SqlServerId
        {
            get
            {
                return this._SqlServerId;
            }
            set
            {
                this.OnSqlServerIdChanging(value);
                this._SqlServerId = value;
                this.OnSqlServerIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _SqlServerId;
        partial void OnSqlServerIdChanging(string value);
        partial void OnSqlServerIdChanged();
        /// <summary>
        /// There are no comments for Property SqlServerName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string SqlServerName
        {
            get
            {
                return this._SqlServerName;
            }
            set
            {
                this.OnSqlServerNameChanging(value);
                this._SqlServerName = value;
                this.OnSqlServerNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _SqlServerName;
        partial void OnSqlServerNameChanging(string value);
        partial void OnSqlServerNameChanged();
        /// <summary>
        /// There are no comments for Property SqlServerDatabase in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string SqlServerDatabase
        {
            get
            {
                return this._SqlServerDatabase;
            }
            set
            {
                this.OnSqlServerDatabaseChanging(value);
                this._SqlServerDatabase = value;
                this.OnSqlServerDatabaseChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _SqlServerDatabase;
        partial void OnSqlServerDatabaseChanging(string value);
        partial void OnSqlServerDatabaseChanged();
        /// <summary>
        /// There are no comments for Property SubScriptionId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string SubScriptionId
        {
            get
            {
                return this._SubScriptionId;
            }
            set
            {
                this.OnSubScriptionIdChanging(value);
                this._SubScriptionId = value;
                this.OnSubScriptionIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _SubScriptionId;
        partial void OnSubScriptionIdChanging(string value);
        partial void OnSubScriptionIdChanged();
        /// <summary>
        /// There are no comments for Property ResourceGroup in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string ResourceGroup
        {
            get
            {
                return this._ResourceGroup;
            }
            set
            {
                this.OnResourceGroupChanging(value);
                this._ResourceGroup = value;
                this.OnResourceGroupChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ResourceGroup;
        partial void OnResourceGroupChanging(string value);
        partial void OnResourceGroupChanged();
        /// <summary>
        /// There are no comments for Property StorageAccountName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string StorageAccountName
        {
            get
            {
                return this._StorageAccountName;
            }
            set
            {
                this.OnStorageAccountNameChanging(value);
                this._StorageAccountName = value;
                this.OnStorageAccountNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _StorageAccountName;
        partial void OnStorageAccountNameChanging(string value);
        partial void OnStorageAccountNameChanged();
        /// <summary>
        /// There are no comments for Property StorageAccountKey in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string StorageAccountKey
        {
            get
            {
                return this._StorageAccountKey;
            }
            set
            {
                this.OnStorageAccountKeyChanging(value);
                this._StorageAccountKey = value;
                this.OnStorageAccountKeyChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _StorageAccountKey;
        partial void OnStorageAccountKeyChanging(string value);
        partial void OnStorageAccountKeyChanged();
        /// <summary>
        /// There are no comments for Property AzureFileShare in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string AzureFileShare
        {
            get
            {
                return this._AzureFileShare;
            }
            set
            {
                this.OnAzureFileShareChanging(value);
                this._AzureFileShare = value;
                this.OnAzureFileShareChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _AzureFileShare;
        partial void OnAzureFileShareChanging(string value);
        partial void OnAzureFileShareChanged();
        /// <summary>
        /// There are no comments for Property Deployments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Collections.ObjectModel.Collection<global::RapidAPI.Models.Deployment> Deployments
        {
            get
            {
                return this._Deployments;
            }
            set
            {
                this.OnDeploymentsChanging(value);
                this._Deployments = value;
                this.OnDeploymentsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.Collection<global::RapidAPI.Models.Deployment> _Deployments = new global::System.Collections.ObjectModel.Collection<global::RapidAPI.Models.Deployment>();
        partial void OnDeploymentsChanging(global::System.Collections.ObjectModel.Collection<global::RapidAPI.Models.Deployment> value);
        partial void OnDeploymentsChanged();
    }
        /// <summary>
        /// There are no comments for DeploymentSingle in the schema.
        /// </summary>
    public partial class DeploymentSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Deployment>
    {
        /// <summary>
        /// Initialize a new DeploymentSingle object.
        /// </summary>
        public DeploymentSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new DeploymentSingle object.
        /// </summary>
        public DeploymentSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new DeploymentSingle object.
        /// </summary>
        public DeploymentSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Deployment> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Project in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::RapidAPI.Models.ProjectSingle Project
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Project == null))
                {
                    this._Project = new global::RapidAPI.Models.ProjectSingle(this.Context, GetPath("Project"));
                }
                return this._Project;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::RapidAPI.Models.ProjectSingle _Project;
    }
        /// <summary>
        /// There are no comments for Deployment in the schema.
        /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    public partial class Deployment : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new Deployment object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="status">Initial value of Status.</param>
        /// <param name="startedAt">Initial value of StartedAt.</param>
        /// <param name="finishedAt">Initial value of FinishedAt.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static Deployment CreateDeployment(int ID, global::RapidAPI.Models.DeploymentStatus status, global::System.DateTimeOffset startedAt, global::System.DateTimeOffset finishedAt)
        {
            Deployment deployment = new Deployment();
            deployment.Id = ID;
            deployment.Status = status;
            deployment.StartedAt = startedAt;
            deployment.FinishedAt = finishedAt;
            return deployment;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property ProjectId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> ProjectId
        {
            get
            {
                return this._ProjectId;
            }
            set
            {
                this.OnProjectIdChanging(value);
                this._ProjectId = value;
                this.OnProjectIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _ProjectId;
        partial void OnProjectIdChanging(global::System.Nullable<int> value);
        partial void OnProjectIdChanged();
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::RapidAPI.Models.DeploymentStatus Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this._Status = value;
                this.OnStatusChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::RapidAPI.Models.DeploymentStatus _Status;
        partial void OnStatusChanging(global::RapidAPI.Models.DeploymentStatus value);
        partial void OnStatusChanged();
        /// <summary>
        /// There are no comments for Property StartedAt in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.DateTimeOffset StartedAt
        {
            get
            {
                return this._StartedAt;
            }
            set
            {
                this.OnStartedAtChanging(value);
                this._StartedAt = value;
                this.OnStartedAtChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.DateTimeOffset _StartedAt;
        partial void OnStartedAtChanging(global::System.DateTimeOffset value);
        partial void OnStartedAtChanged();
        /// <summary>
        /// There are no comments for Property FinishedAt in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.DateTimeOffset FinishedAt
        {
            get
            {
                return this._FinishedAt;
            }
            set
            {
                this.OnFinishedAtChanging(value);
                this._FinishedAt = value;
                this.OnFinishedAtChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.DateTimeOffset _FinishedAt;
        partial void OnFinishedAtChanging(global::System.DateTimeOffset value);
        partial void OnFinishedAtChanged();
        /// <summary>
        /// There are no comments for Property FailureReason in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string FailureReason
        {
            get
            {
                return this._FailureReason;
            }
            set
            {
                this.OnFailureReasonChanging(value);
                this._FailureReason = value;
                this.OnFailureReasonChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _FailureReason;
        partial void OnFailureReasonChanging(string value);
        partial void OnFailureReasonChanged();
        /// <summary>
        /// There are no comments for Property Project in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::RapidAPI.Models.Project Project
        {
            get
            {
                return this._Project;
            }
            set
            {
                this.OnProjectChanging(value);
                this._Project = value;
                this.OnProjectChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::RapidAPI.Models.Project _Project;
        partial void OnProjectChanging(global::RapidAPI.Models.Project value);
        partial void OnProjectChanged();
    }
        /// <summary>
        /// There are no comments for DeploymentStatus in the schema.
        /// </summary>
    public enum DeploymentStatus
    {
        InProgress = 0,
        PackagingApp = 1,
        ProvisioningResourceGroup = 2,
        ProvisioningApp = 3,
        ProvisioningDatabase = 4,
        DeployingApp = 5,
        Complete = 6,
        Failed = 7
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::RapidAPI.Models.Project as global::RapidAPI.Models.ProjectSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::RapidAPI.Models.ProjectSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::RapidAPI.Models.Project> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::RapidAPI.Models.ProjectSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::RapidAPI.Models.Project as global::RapidAPI.Models.ProjectSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::RapidAPI.Models.ProjectSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::RapidAPI.Models.Project> _source,
            int id)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::RapidAPI.Models.ProjectSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::RapidAPI.Models.Deployment as global::RapidAPI.Models.DeploymentSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::RapidAPI.Models.DeploymentSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::RapidAPI.Models.Deployment> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::RapidAPI.Models.DeploymentSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::RapidAPI.Models.Deployment as global::RapidAPI.Models.DeploymentSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::RapidAPI.Models.DeploymentSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::RapidAPI.Models.Deployment> _source,
            int id)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::RapidAPI.Models.DeploymentSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
    }
}
namespace Default
{
        /// <summary>
        /// There are no comments for Container in the schema.
        /// </summary>
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public Container(global::System.Uri serviceRoot) :
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Projects in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::RapidAPI.Models.Project> Projects
        {
            get
            {
                if ((this._Projects == null))
                {
                    this._Projects = base.CreateQuery<global::RapidAPI.Models.Project>("Projects");
                }
                return this._Projects;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::RapidAPI.Models.Project> _Projects;
        /// <summary>
        /// There are no comments for Deployments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::RapidAPI.Models.Deployment> Deployments
        {
            get
            {
                if ((this._Deployments == null))
                {
                    this._Deployments = base.CreateQuery<global::RapidAPI.Models.Deployment>("Deployments");
                }
                return this._Deployments;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::RapidAPI.Models.Deployment> _Deployments;
        /// <summary>
        /// There are no comments for Projects in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToProjects(global::RapidAPI.Models.Project project)
        {
            base.AddObject("Projects", project);
        }
        /// <summary>
        /// There are no comments for Deployments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToDeployments(global::RapidAPI.Models.Deployment deployment)
        {
            base.AddObject("Deployments", deployment);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private const string filePath = @"RapidApi ServiceCsdl.xml";

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader();
                try
                {
                    global::System.Collections.Generic.IEnumerable<global::Microsoft.OData.Edm.Validation.EdmError> errors;
                    global::Microsoft.OData.Edm.IEdmModel edmModel;

                    if (!global::Microsoft.OData.Edm.Csdl.CsdlReader.TryParse(reader, false, out edmModel, out errors))
                    {
	                    global::System.Text.StringBuilder errorMessages = new System.Text.StringBuilder();
	                    foreach (var error in errors)
	                    {
		                    errorMessages.Append(error.ErrorMessage);
		                    errorMessages.Append("; ");
	                    }
	                    throw new global::System.InvalidOperationException(errorMessages.ToString());
                    }

                    return edmModel;
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::System.Xml.XmlReader CreateXmlReader()
            {
                try
                {
                    var assembly = global::System.Reflection.Assembly.GetExecutingAssembly();
                    var resourcePath = global::System.Linq.Enumerable.Single(assembly.GetManifestResourceNames(), str => str.EndsWith(filePath));
                    global::System.IO.Stream stream = assembly.GetManifestResourceStream(resourcePath);
                    return global::System.Xml.XmlReader.Create(new global::System.IO.StreamReader(stream));
                }
                catch(global::System.Xml.XmlException e)
                {
                    throw new global::System.Xml.XmlException("Failed to create an XmlReader from the stream. Check if the resource exists.", e);
                }
            }
        }
        /// <summary>
        /// There are no comments for CreateProject in the schema.
        /// </summary>
        public virtual global::Microsoft.OData.Client.DataServiceActionQuerySingle<global::RapidAPI.Models.Deployment> CreateProject(string AppId, string SubscriptionId, string Schema)
        {
            return new global::Microsoft.OData.Client.DataServiceActionQuerySingle<global::RapidAPI.Models.Deployment>(this, this.BaseUri.OriginalString.Trim('/') + "/CreateProject", new global::Microsoft.OData.Client.BodyOperationParameter("AppId", AppId),
                    new global::Microsoft.OData.Client.BodyOperationParameter("SubscriptionId", SubscriptionId),
                    new global::Microsoft.OData.Client.BodyOperationParameter("Schema", Schema));
        }
    }
}
